### ISSUE TITLE
Cosmetics Interfering with feed

### ISSUE THREAD

**Issue by xsigsig** [The0therOne/Helmet_Cameras#1]
Cosmetics on the players heads are cause the camera view to be obscured (such as the googly eyes and shades). It would be great if there was a feature to unrender them in the camera feed or some other optional solution that can be modified in the config.

**Comment by ShadowRocks2** [comment]
To specify, the cosmetics that MoreCompany adds

**Comment by The0therOne** [comment]
Thanks for your feedback. I'll try to fix it.

**Comment by xsigsig** [comment]
I apologize. I've only ever played the game with More Company and assumed it was part of the base game, not a mod. Regardless, More Company has been updated with a feature that allows you to make other players' cosmetics invisible, making this request mostly obsolete.

**Comment by TwoPointInfinity** [comment]
but i want to see my friends cosmetics, it gives them character and helps me identify them. 
Seeing the other player's cosmetics is why they put them on, and its why i put them on, so they can see what i'm wearing.
