### ISSUE TITLE
Excessive info logging

### ISSUE THREAD

**Issue by nh-99** [The0therOne/Helmet_Cameras#10]
Currently it seems that there is an info message being logged in the update loop that says `[Info   : Unity Log] [HELMET_CAMERAS] Player in ship! Rendering the camera...`. This is washing out all of the other log messages, making it hard to see any other mods. I think it should either a) be removed or b) changed to a debug log.

**Comment by khionu** [comment]
Or better yet, rate limited. If this is indicative of when the check is made, that's way too much. For a sufficiently-seamless experience, could check every 100ms.

**Comment by The0therOne** [comment]
Thanks for issue!
Ok, no problems, i can just remove it.

**Comment by Ashesh3** [comment]
Came here to make the same issue, glad to see it being already addressed!

**Comment by The0therOne** [comment]
Done! Check 2.1.5
