### ISSUE TITLE
[Feature Request] Purchasable Ship Upgrade

### ISSUE THREAD

**Issue by Slugiish** [The0therOne/Helmet_Cameras#12]
Hi, I love the mod but the group I play with have some worries about using it due the the fact that it undeniably gives the ship computer guy more information than they could otherwise have and because of that makes them more capable at their job and thus lowers the difficulty of the game somewhat. Because of that I would greatly appreciate if it was possible to have a config option that makes the mod only go into effect after purchasing a head camera ship upgrade for some configurable cost, that way the added feature feels earned and the extra ease it gives feels offset by the difficulty to obtain it. I also however totally understand if this is outside of the scope of what you want to do with the mod or is too difficult to implement. Thank you for your time in reading my feature request, I hope to hear back from you soon.

**Comment by The0therOne** [comment]
Hi!
Let me think about ways of making it.
Possibly I need to use LethalLib or something...

**Comment by Slugiish** [comment]
Yay, thank you for even trying. I'll be waiting in anticipation.

**Comment by The0therOne** [comment]
After some researches about it:
1. Its really difficult to make it without ready libs.
2. And it transform my mod from client side to server side because of upgrade and credits sync.
I will continue check more ways or search some help with it.
