### ISSUE TITLE
[BUG] It doesn't work for non host players

### ISSUE THREAD

**Issue by SirPrepu** [The0therOne/Helmet_Cameras#13]
I've been testing this mod because I love the feature but It doesn't work for my friends when I host a game, same for me when they host a game.

**Comment by The0therOne** [comment]
Its not server side mod. Every player need to install it

**Comment by The0therOne** [comment]
Did everyone install it?

**Comment by Lallering** [comment]
i have the same issue, yesterday it was working perfectly and today it stopped working, we all have the mod installed

**Comment by The0therOne** [comment]
Its very strange case. Possibly rare BepInEx bug or helmet camera mod... Its client side mod. It does not relate to "who is host".
Did you try restart the game to fix it?
Or what did you do to fix it? Or bug unfixable for you?

**Comment by SirPrepu** [comment]
In my case everyone has the mod installed but only the host mod works, It's weird but I don't know exactly what's causing it, I tried the Solos Body Cam mod that you mentioned in your releases notes and works fine for everyone.
I'm using other mods but I'll try with only this to see if another mod is causing a conflict.

**Comment by Lallering** [comment]
It's the same with me, the strange thing is that the mod was working perfectly, but suddenly the video stopped showing on the monitor and only the host can see it, today we will try again to see if it was something strange with the BepInEx

**Comment by The0therOne** [comment]
If you get it error one more time, please send me bepinex log

**Comment by Lallering** [comment]
We couldn't get it to work, there is simply no error message when you enter the game as non host, the message about initializing the camera does not appear like when you are a Host. we had to switch to SoloBodycams :/

**Comment by SirPrepu** [comment]
Yea it's the same for me, no error message and the non host players respond with the mod just fine but it somehow doesn't work.
I'm currently testing which mod causes conflict because it works perfectly when using it alone. I'll post here as soon as I figure it out.

**Comment by SirPrepu** [comment]
Well, I might have found out the culprit:
https://thunderstore.io/c/lethal-company/p/Mom_Llama/Lethal_Company_Enhancer/

BUT, It only causes conflict if you change this setting from "false" to "true" within its config file:

\## Unlocks a few of the cheaper suits from the start so your crew has options.
\## Host Required: Yes
\# Setting type: Boolean
\# Default value: false
bUnlockSuits = false

Somehow this setting causes this problem, at least on my end, I tested again with my mod pack with this specific setting set to false and the helmet camera mod works perfectly.

Btw I used two instances of LC in the same pc and start a LAN game so I have the exact same mods and bepinex version (the latest as of today)

**Comment by The0therOne** [comment]
Thanks for your tests!
I will check what reason of conflict could be with LC Enhancer

**Comment by The0therOne** [comment]
I think we can close your issue with your conlusion about mod conflict. But I will check what I can do with this problem.
