### ISSUE TITLE
[BUG] Ship Camera Frozen When Spectating

### ISSUE THREAD

**Issue by Metro-Shroomin** [The0therOne/Helmet_Cameras#14]
After you've died, if you're spectating a player that's within the ship, the ship camera will remain frozen.

**Comment by The0therOne** [comment]
Hi! Thanks for issue.
Its because you are not in ship. You died. I will think about it, how can i change it. IF i can.

**Comment by The0therOne** [comment]
I think I can change it. Need some tests and if it will work, will update it as soon as possible.
