### ISSUE TITLE
Helmet cameras as a ship upgrade?

### ISSUE THREAD

**Issue by ThomTom0** [The0therOne/Helmet_Cameras#17]
Hello,

My friends and I really like the mod you’ve created, but we think it is very overpowered. We then thought that if it was a ship upgrade of at least $500 it’d be fair.

Are you planning to make it into a ship upgrade or even making a separate version of the mod with it as an upgrade? If not, I highly suggest you do!

Thanks.

**Comment by ProblemFactory** [comment]
I believe making it an upgrade will require server-side change? Keeping it client-only is better imo.

**Comment by The0therOne** [comment]
Some players already suggest it to me before... But there are 2 reasons, why I will not do it.
1) My mod will become server side mod. Its not good for many players.
2) Its really difficult to make it. Using libs, sync info about credits and upgrade, custom upgrades. I just havent got enough time for it.
I think, some modders will make libs soon to make new custom upgrades and syncing it easier.
Sorry for that.
