### ISSUE TITLE
Model disapper in the camera view.

### ISSUE THREAD

**Issue by rto700** [The0therOne/Helmet_Cameras#18]
The body model will disapper in the camera view of the radar booster when you are close to it. I have not test in multiplayer, so I do not know whether it is the same for the players camera.

**Comment by The0therOne** [comment]
Only body? Or whole player model?

**Comment by rto700** [comment]
Only the body part, I can still see my arms and helmet.

**Comment by The0therOne** [comment]
Its ingame behaivour with layer mask. If local player look at himself, his body will disappear. Its unfixable.

**Comment by rto700** [comment]
I also tried another similar mod "Solos_Bodycams by CapyCat", it can show the whole body in this case, but with an aditional pair of arm(probabaly the layer mask).

**Comment by rto700** [comment]
And when I combined "Solos_Bodycams by CapyCat" with "MirrorDecor by quackandcheese", the extra arms just disappered and it shows a proper model, but it also vanished the shadow of the body part. Hope these are helpful.

**Comment by rto700** [comment]
By the way, is that possible to add compatibility with "BetterSecurityCameras by stormytuna"?

**Comment by The0therOne** [comment]
Now its not compatible?
How did it expressed?

**Comment by rto700** [comment]
It only shows the view of the security camera after landing on the moons.
