### ISSUE TITLE
Please Optimize

### ISSUE THREAD

**Issue by MalacoX** [The0therOne/Helmet_Cameras#19]
I love this mod it's amazing, it makes being the terminal guy fun. But the performance drop is so severe that I hope you can optimize this mod more when inside the ship, maybe culling. or LOD changes can help? Of course, if I'm asking too much that's ok and I don't want you to think that I'm just whining about the performance or anything, I'll still use the mod regardless of whether you change anything.

**Comment by The0therOne** [comment]
Hi! Thanks for you words and support! I really appreciate it.
I understand you. I was playing today with my friends and my friend told me that his fps were around ~30 inside the ship.
For now, I cant understand how to optimize it more... Actually your fps = your standart ingame fps - camera fps (in config). I can try to play around settings of camera or something else. Due to lack of experience, i cant optimize it fast, sorry for that.

**Comment by MalacoX** [comment]
Completely fine! This is probably one of, if not the best mod for Lethal Company terminal players, do take time. Happy Holidays!

**Comment by The0therOne** [comment]
Thanks a lot!
Happy Holidays too!

**Comment by The0therOne** [comment]
Can you check fps on moon inside the ship without my mod and tell me how many fps will you have?

**Comment by MalacoX** [comment]
I'm sorry I didn't check GitHub for a while, I'll check... (Edit: I have the FPS limiter on btw.)

I get around 60-120 FPS without the mod, with the mod I get around 30 FPS looking at and away from the screen. And I have a 3090 and I don't exactly remember the model of my CPU but it's decent enough to where it shouldn't lag so I don't think it's a hardware issue.

**Comment by The0therOne** [comment]
My spec: 3070
CPU i7 12700
I just cant reproduce it... Without mod my fps is 110, with mod my fps is 95-100.
Its really strange situation...

**Comment by The0therOne** [comment]
Is it still luggy for you? Looks like something happened after game update, and switching camera fps in cfg dont affect fps in game...

**Comment by uffemcev** [comment]
I have a similar problem. FPS also drops on the ship with this mod.

**Comment by The0therOne** [comment]
Its normal if your fps drop = camera fps value from config. If its more than camera fps its not ok.
How many camera fps did you set?
