### ISSUE TITLE
Feature Request: FPS Limit in config

### ISSUE THREAD

**Issue by DJFarr** [The0therOne/Helmet_Cameras#2]
Hi, 
I feel strongly that having the ability to lower the fps would make this a more immersive/authentic experience.
Would this be a possible addition to add, on top of the Resolution config?
Thanks

**Comment by The0therOne** [comment]
Hi.
Good news, currently I am working with adding that setting ;)

**Comment by DJFarr** [comment]
Awesome!
thanks

**Comment by The0therOne** [comment]
Done! Check 2.1.0
