### ISSUE TITLE
FPS drops in the ship but only when landing on a moon

### ISSUE THREAD

**Issue by rsirantoine** [The0therOne/Helmet_Cameras#20]
As title says, with this mod, the FPS is just fine in the ship when not on a moon but as soon as you land on a moon it goes very laggy. I don't know if this was already reported but I prefer to say it to help the developer of this mod :)

**Comment by The0therOne** [comment]
Just check fps on moon inside the ship without my mod and tell me how many fps you have.

**Comment by rsirantoine** [comment]
Without your mod, FPS revolves around 110. With the mod, it's around 50FPS.
Without being on a moon and without the mod, it's around 150 while with the mod, it's ~80FPS. 

![image](https://github.com/The0therOne/Helmet_Cameras/assets/154819387/e8319091-a9e8-44d7-824c-356405734e07)
![image](https://github.com/The0therOne/Helmet_Cameras/assets/154819387/246d9bd6-7ee4-496d-a7b6-2eac9ec8154c)

**Comment by rsirantoine** [comment]
Could be worth to tell my specs
CPU : AMD Ryzen 3 3200G
GPU : GTX 1660 Super
2x16GB RAM

**Comment by The0therOne** [comment]
Just tested it myself.
With mod on moon inside the ship 95-100
Without mod on moon inside the ship 110

I cant understand why. Continue research it... Maybe because of your specs, idk.
My specs 3070ti and i7 12700. I am trying to optimize it more, but its really difficult. Because i cant reproduce problem. For me its just around 10 fps difference...

**Comment by The0therOne** [comment]
It looks like you have 60 camera fps in my cfg file

**Comment by The0therOne** [comment]
Can you screenshot me your cfg file?

**Comment by rsirantoine** [comment]
![image](https://github.com/The0therOne/Helmet_Cameras/assets/154819387/ec5b53a0-4057-4164-8e4c-b276971bc345)
There you go

**Comment by rsirantoine** [comment]
btw, tried lowering cameraFps to 15 but it's still kinda laggy in the ship when landed on a moon

**Comment by The0therOne** [comment]
With camera fps 30 and 15 have you got different ingame fps?

**Comment by rsirantoine** [comment]
Idk, seems the same, I'll test it out later because I have to put the Steam FPS counter back on

**Comment by The0therOne** [comment]
Between 15 and 30 camera fps values, you ingame fps must change around ~15 fps. Please, test it as soon as you can :)
Test it with 15, 30, 60 fps and tell me you ingame fps with all these 3 settings. It will help me understand what is going on

**Comment by The0therOne** [comment]
You didnt reply me :(
If you want to try to fix it with me, reopen it.
