### ISSUE TITLE
[SUGGESTION] Make it a ship upgrade

### ISSUE THREAD

**Issue by Nyxlanders** [The0therOne/Helmet_Cameras#21]
Would be better if you had to buy the camera system in the shop, instead of starting with it.

**Comment by The0therOne** [comment]
Hi!
I dont plan to add it, because it will change my mod from client side mod to server side (Its difficult to implement it and players cant play with mod, if host dont install it).
A lot of players prefer client side mod.
Sorry for that! Happy holidays!
