### ISSUE TITLE
Helmet Cams Making My (server host) Head Big

### ISSUE THREAD

**Issue by ThaBestStriker** [The0therOne/Helmet_Cameras#22]
Unsure if this is a problem between mods, but my head is large while being server host. Others playing don't seem to experience this issue. https://www.youtube.com/watch?v=Qu3qqwYUKao

**Comment by The0therOne** [comment]
When you look at yourself through camera, your head is big and body disappear. Its problem with layer masks. Its not huge problem, i guess. As soon as i will have time, i will try to fix it.
Happy holidays!
