### ISSUE TITLE
Camera obstructed when using some model replacers.

### ISSUE THREAD

**Issue by Lilith-Crimeow** [The0therOne/Helmet_Cameras#24]
In particular, Lethal Creature has significant changes to the playermodel - when i view other players, depending on where they're looking, the camera may be obstructed.
![Lethal_Company_GOeqlWBicY](https://github.com/The0therOne/Helmet_Cameras/assets/80209203/1ff2144a-fda9-4967-bee6-be18e5203648)

**Comment by The0therOne** [comment]
I know about it, Fixed it with some simple cosmetics, but not for player models. I think i cant really fix it with big models like on your screenshot. Will try fix it when i will have time for it. Thanks for issue!
