### ISSUE TITLE
camera wont switch 

### ISSUE THREAD

**Issue by shrimpmakima** [The0therOne/Helmet_Cameras#25]
pressed switch camera but camera wont switch to other player. stuck on myself's camera

**Comment by The0therOne** [comment]
Cant reproduce it.
Maybe not compatible with some of your mods...
Try to use only my mod enabled for testing.

**Comment by The0therOne** [comment]
Please, answer me about problem.
Is it still dont switch for you?

**Comment by shrimpmakima** [comment]
if i remove all mod it seems working fine

Timur ***@***.***>于2024年1月10日 周三下午8:59写道：

**Comment by The0therOne** [comment]
You can try to find mod that not compatible with my mod and i can try to fix it.

**Comment by shrimpmakima** [comment]
im using a mod bundle it has so many mods
:<

Timur ***@***.***>于2024年1月10日 周三下午9:03写道：

**Comment by shrimpmakima** [comment]
I will just leave it sometimes it works fine ty for your help

虾。 ***@***.***>于2024年1月10日 周三下午9:04写道：

**Comment by The0therOne** [comment]
Ok. If you find mod that not compatible with helmet cameras, please tell me :)
Goodluck!
