### ISSUE TITLE
issues with 2.0

### ISSUE THREAD

**Issue by Jaredmf** [The0therOne/Helmet_Cameras#3]
Had some UI issues when playing with this mod. Scanning with right click didn't work, hold indicator didn't show up, voice boxes when dead didn't show up. Cannot fully confirm that it was solely this mod's fault, but disabling it fixed all our issues.

Other installed mods are:

![r2modman_c3VgWoD1Im](https://github.com/The0therOne/Helmet_Cameras/assets/10677813/216f5523-1c0c-4a59-8372-291496dc16f4)

**Comment by The0therOne** [comment]
Check BepInEx config file and tell me what value do you have in HideManagerGameObject? Is it false or true?
I can say with 100% confidence that is not my mod. I guess it can be not compatible with some mod or something with it. But I dont change something with ui. Just adding camera and change position of camera.

**Comment by Jaredmf** [comment]
it's set to false

**Comment by The0therOne** [comment]
Ok, thanks. Just to check.
So I think its not compatible with some of mods or vanilla rare bug. I heard about UI bugs. Sometimes it happens without mods, sometimes it happens with other mods, not cameras mods.
