### ISSUE TITLE
Marked as depreciated?

### ISSUE THREAD

**Issue by DravenXD** [The0therOne/Helmet_Cameras#31]
The mod has been marked as depreciated. Is there an alternative we are supposed to use?
![Untitled](https://github.com/user-attachments/assets/0d1975c1-0ef6-4eca-88be-ce608d2ab2ed)

**Comment by The0therOne** [comment]
Hi!
I think it is error or something.
I undeprecated it. You can continue use it, if you want :)
p.s. Just checked it in game, its working.
