### ISSUE TITLE
[Feature Request] Better Compatibility with MoreCompany, and Accessories. 

### ISSUE THREAD

**Issue by TwoPointInfinity** [The0therOne/Helmet_Cameras#4]
[MoreCompany](https://thunderstore.io/c/lethal-company/p/notnotnotswipez/MoreCompany/) is a mod that expands the player count for the lobby. 
This mod also adds **_cosmetics_**. These cosmetics include things like hats, clothing, and **_facial accessories_**. 
**It is also the 2nd most downloaded mod for lethal company.**

Many of the accessories from MoreCompany block the helmet camera, and as more mods come out that add accessories to the players this will continue to be an issue. 

I'm unsure of a great way to fix this conflict, but maybe moving the camera position further forward or to the side could be an easy fix, as i don't know if the cosmetics will be able to be disabled just for the camera vision. But without know what cosmetics the future holds its hard to say if new cosmetics will just block a moved camera as well.

**Comment by TwoPointInfinity** [comment]
oh haha, i just saw the closed comment someone else already made about this same issue. I hope that its something that can be looked into.

**Comment by The0therOne** [comment]
Hi! Thanks for "issue"!
Agree with you that helmet cameras should be compatible with more company.

I'll try to fix it.

**Comment by The0therOne** [comment]
Please check 2.1.1 ver. and tell me about problem. It should be fixed now or will be better than before.

**Comment by TwoPointInfinity** [comment]
okay awesome, this seems to work. The camera isnt blocked but if the camera sees other players they are missing body parts like their torso. Better than not being able to see.

**Comment by The0therOne** [comment]
Thanks!
So, I need golden mean. Can you, please, describe how many meters away camera dont render body parts?

**Comment by The0therOne** [comment]
Ok, nvm. Just tested it myself. Trying to fix it and find that golden mean...

**Comment by The0therOne** [comment]
Cant test locally with more company :(

**Comment by The0therOne** [comment]
Figured out that without body parts only localPlayer, if someone look at you. Other player are ok.

**Comment by TwoPointInfinity** [comment]
i understand though, that if you see yourself through someone else's camera then y our body will not load properly. But if they look at the monitor they do not see that problem

**Comment by The0therOne** [comment]
Is it good result of fix?
Should i change something about it?
