### ISSUE TITLE
FPS Flickering Issue

### ISSUE THREAD

**Issue by xoJason** [The0therOne/Helmet_Cameras#5]
I've had this problem where lowering the FPS of the camera in the config makes lights flicker and making it higher (like FPS I normally wouldn't have, basically 70-80 range) seems to fix it, but then I'm taking a performance hit anyway. I've seen another person in the modding discord have this problem as well.

**Comment by The0therOne** [comment]
I will test it. What fps did you set for flickering light?

**Comment by xoJason** [comment]
Anything below 70 which was my average FPS at the time was giving me flickering light. The more I went down the flashier it got

**Comment by The0therOne** [comment]
And what mods did you install?
I mean, why are you sure that problem with helmet cameras? Give me details please if you can! :)

**Comment by xoJason** [comment]
I was using my modpack McDoobies which has mods like HDLethalCompany in it. It seemed as though the rate of the flickering was tied to the FPS the camera was at. It was flickering when looking at the sun and the lights in the ship flickered as well. Each time I changed the config to 70 or above the flickering was gone and disabling the mod also fixed the issue, and I don't believe me or my friends had any flickering problems before the latest update.

**Comment by The0therOne** [comment]
Ok, I will try to fix it. Thanks for issue.

**Comment by The0therOne** [comment]
Can you try to reproduce flickering with lowering fps and without HDcompany please?

**Comment by The0therOne** [comment]
Just tested it with 15 fps and cant reproduce it.
I will try test it with HDcompany

**Comment by The0therOne** [comment]
If you dont mind, can you give your discord, please?
I need your config of HDCompany and Helmet Cameras.

I cant reproduce it with HDCompany and without it with 15 fps...

**Comment by xoJason** [comment]
Sure my discord is .j_son

**Comment by The0therOne** [comment]
Wrote you in discord

**Comment by xoJason** [comment]
All fixed with the new 2.1.2 update, issue was conflict with FOVAdjust and it's hideVisor setting. Thanks a lot!
