### ISSUE TITLE
[Suggestion] Disable rendering for performance

### ISSUE THREAD

**Issue by GliitchedEntity** [The0therOne/Helmet_Cameras#6]
The 2.1.3 update did improve performance significantly (now it's even more performant than solo's bodycams when outside of the ship)
As of 2.1.3 update when leaving the ship, camera stops moving, but still renders things. The idea is to disable camera object as a whole while outside of ship.

**Comment by The0therOne** [comment]
Thanks for feedback and suggestion, will try it.

**Comment by The0therOne** [comment]
Sorry, was busy for modding.
Now I checked it, and camera not just stop moving, Camera component set off when player outside of ship. If you told me exactly about it, its done already, i guess.
Or did you tell me about turning off the whole game object with camera component?

**Comment by GliitchedEntity** [comment]
Doing more tests, i found out "Fov abjust" mod caused the camera to keep rendering things even when outside of the ship
Sorry for not testing it more carefully.
Feel free to close this issue

**Comment by GliitchedEntity** [comment]
Everything works well now, thanks for keeping mod supported and optimized <3

**Comment by GliitchedEntity** [comment]
Done some more testing, with helmet cameras only installed
Seems like it still have a chance to keep rendering while outside of the ship
Here are screenshots with descriptions of what's happening https://imgur.com/a/SqFzRYK
another way to test it is setting high fps and rendering quality in config and checking gpu load each time leaving the ship
when camera keeps rendering, my gpu load is at 97%
when it stops rendering correctly, it's at 70%

**Comment by The0therOne** [comment]
Thanks for your testing. I can change something with turning off game object with camera and send you to test, you dont mind.
You can leave here your discord and i will send updated plugin to test, ok?

**Comment by GliitchedEntity** [comment]
Sure, here's my discord link
discord.gg/8Cq4kD5y
or you can use the nickname
semiauto1337

**Comment by GliitchedEntity** [comment]
Closing as solved, thanks for support <3
