### ISSUE TITLE
Only host can see the helmet cams

### ISSUE THREAD

**Issue by DJFarr** [The0therOne/Helmet_Cameras#7]
I have a long list of mods, including MoreCompany, but it seems like only the host (me) can see the cameras on the screen.
I am using Thunderstore ModManager, and sharing my profile to friends using the profile export-code.
the HideGameManagerObject is set to true currently for all people.

**Comment by The0therOne** [comment]
Why are you using HideGameManagerObject true? There's a reason for this?

**Comment by DJFarr** [comment]
It was being set to True after each game launch, which i have found out was because of the CustomSounds mod editing my config file.
I will test again with my group tomorrow with the value set to false.

**Comment by The0therOne** [comment]
Ok, thanks! Will wait your answer

**Comment by ficarra1002** [comment]
For me, whoever connects 2nd seems to not have the camera. Host, 3, and 4 see it fine.

**Comment by The0therOne** [comment]
1. Check bepinex console for errors, if you can.
2. If Host, 3, 4 players see cameras, and you are not, thats propably not helmet camera's bug. Its can be conflict with other mods, or just bug with bepinex, or just bug with unity scene loading. Thats why I need your, for example, log.

**Comment by The0therOne** [comment]
Issuer didnt answer for 2 days. Will close issue. If you need my help, you can reopen issue.
