### ISSUE TITLE
[Bug] Light flicker a lot inside of ship and with any light source when fullscreen

### ISSUE THREAD

**Issue by otDan** [The0therOne/Helmet_Cameras#8]
All the game lights flicker whenever moving around close to any light source with this mods latest version installed when playing in fullscreen, going back to window mode solves it but it's definitely not ideal.

**Comment by The0therOne** [comment]
Thanks for your "issue".
Can you write me your discord and give me a list of mods and folder with configs? I cant help you without it.

**Comment by The0therOne** [comment]
Issuer didnt answer
