### ISSUE TITLE
Error: Hardware Not Supported For Volumetric Materials (Helmet Cameras)

### ISSUE THREAD

**Issue by glycemias** [The0therOne/Helmet_Cameras#9]
Need help fixing Hardware Not Supported For Volumetric Materials for Lethal Company. It then causes a static in the voice chat.

**Comment by The0therOne** [comment]
Hi!
My mod just changing position of camera. It cant be a problem like that.
Some possible reasons:
1. Unity bug
2. BepInEx bug or something (I saw same problem with other mods in Lethal Company mod community discord)
Its not a problem. You can ignore it and continue to play or hide console in BepInEx cfg, if you dont need it.
3. Maybe some conflicts with unity engine and your hardware... But its not that case.

I really dont know how can I help you with your problem now. But I will google about it, and if I can find something, I will help you.
